version: '3.8'

services:
  w1:
    build: { context: ../../, dockerfile: services/witness-node/Dockerfile }
    environment: [ WITNESS_ID=w1, PORT=8091 ]
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 5s
      timeout: 3s
      retries: 20
  w2:
    build: { context: ../../, dockerfile: services/witness-node/Dockerfile }
    environment: [ WITNESS_ID=w2, PORT=8092 ]
  w3:
    build: { context: ../../, dockerfile: services/witness-node/Dockerfile }
    environment: [ WITNESS_ID=w3, PORT=8093 ]
  w4:
    build: { context: ../../, dockerfile: services/witness-node/Dockerfile }
    environment: [ WITNESS_ID=w4, PORT=8094 ]
  w5:
    build: { context: ../../, dockerfile: services/witness-node/Dockerfile }
    environment: [ WITNESS_ID=w5, PORT=8095 ]

  gateway:
    build: { context: ../../, dockerfile: services/gateway/Dockerfile }
    environment:
      - WITNESSES=http://w1:8091,http://w2:8092,http://w3:8093,http://w4:8094,http://w5:8095
      - QUORUM=4
      - DELTA_MS=2000
    ports: ["8080:8080"]
    depends_on: [w1, w2, w3, w4, w5]