version: '3.8'

services:
  # Atlas Gateway
  gateway:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
    depends_on:
      - witness-1
      - witness-2
      - witness-3
      - witness-4
      - witness-5
    networks:
      - atlas-network
    restart: unless-stopped
    volumes:
      - ../../services/gateway/src:/app/src:ro

  # Witness Node 1 (US East)
  witness-1:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.witness
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WITNESS_ID=w1
      - WITNESS_REGION=us-east-1
      - SECURITY_TRACK=Z
      - DATA_DIR=/app/data
      - LOG_LEVEL=debug
    volumes:
      - witness-1-data:/app/data
      - ../../services/witness-node/src:/app/src:ro
    networks:
      - atlas-network
    restart: unless-stopped

  # Witness Node 2 (US West)
  witness-2:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.witness
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WITNESS_ID=w2
      - WITNESS_REGION=us-west-2
      - SECURITY_TRACK=Z
      - DATA_DIR=/app/data
      - LOG_LEVEL=debug
    volumes:
      - witness-2-data:/app/data
      - ../../services/witness-node/src:/app/src:ro
    networks:
      - atlas-network
    restart: unless-stopped

  # Witness Node 3 (EU West)
  witness-3:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.witness
    ports:
      - "3003:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WITNESS_ID=w3
      - WITNESS_REGION=eu-west-1
      - SECURITY_TRACK=Z
      - DATA_DIR=/app/data
      - LOG_LEVEL=debug
    volumes:
      - witness-3-data:/app/data
      - ../../services/witness-node/src:/app/src:ro
    networks:
      - atlas-network
    restart: unless-stopped

  # Witness Node 4 (AP Southeast)
  witness-4:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.witness
    ports:
      - "3004:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WITNESS_ID=w4
      - WITNESS_REGION=ap-southeast-1
      - SECURITY_TRACK=Z
      - DATA_DIR=/app/data
      - LOG_LEVEL=debug
    volumes:
      - witness-4-data:/app/data
      - ../../services/witness-node/src:/app/src:ro
    networks:
      - atlas-network
    restart: unless-stopped

  # Witness Node 5 (AP Northeast)
  witness-5:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.witness
    ports:
      - "3005:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WITNESS_ID=w5
      - WITNESS_REGION=ap-northeast-1
      - SECURITY_TRACK=Z
      - DATA_DIR=/app/data
      - LOG_LEVEL=debug
    volumes:
      - witness-5-data:/app/data
      - ../../services/witness-node/src:/app/src:ro
    networks:
      - atlas-network
    restart: unless-stopped

  # Web Application
  web:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.web
    ports:
      - "3006:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - NEXT_PUBLIC_GATEWAY_URL=http://gateway:3000
    depends_on:
      - gateway
    networks:
      - atlas-network
    restart: unless-stopped
    volumes:
      - ../../apps/web/src:/app/src:ro

  # Admin Dashboard
  admin:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.admin
    ports:
      - "3007:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - NEXT_PUBLIC_GATEWAY_URL=http://gateway:3000
    depends_on:
      - gateway
    networks:
      - atlas-network
    restart: unless-stopped
    volumes:
      - ../../apps/admin/src:/app/src:ro

volumes:
  witness-1-data:
  witness-2-data:
  witness-3-data:
  witness-4-data:
  witness-5-data:

networks:
  atlas-network:
    driver: bridge
