global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'atlas'
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway:8080
          - w1:8091
          - w2:8092
          - w3:8093
          - w4:8094
          - w5:8095
