version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.54.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.5.0
    ports:
      - "3200:3200"
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml:ro
    command:
      - "-config.file=/etc/tempo/tempo.yml"
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/config.yaml:ro
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    depends_on:
      - tempo
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3030:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    depends_on:
      - prometheus
      - tempo
    restart: unless-stopped
