services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports: ["16686:16686"]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    command: ["--config=/etc/otel/otel-collector.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otel/otel-collector.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus metrics
      - "13133:13133" # health check

  prometheus:
    image: prom/prometheus:v2.54.1
    ports: ["9090:9090"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.4.5
    container_name: observability-grafana-1
    ports: ["3007:3000"]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/Atlas

  w1:
    build:
      context: ..
      dockerfile: services/witness-node/Dockerfile
    environment:
      - PORT=8091
      - WITNESS_ID=w1
      - OTEL_ENABLED=1
      - OTEL_SERVICE_NAME=atlas-w1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports: ["8091:8091"]
    depends_on: []

  w2:
    build:
      context: ..
      dockerfile: services/witness-node/Dockerfile
    environment:
      - PORT=8092
      - WITNESS_ID=w2
      - OTEL_ENABLED=1
      - OTEL_SERVICE_NAME=atlas-w2
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports: ["8092:8092"]
    depends_on: []

  w3:
    build:
      context: ..
      dockerfile: services/witness-node/Dockerfile
    environment:
      - PORT=8093
      - WITNESS_ID=w3
      - OTEL_ENABLED=1
      - OTEL_SERVICE_NAME=atlas-w3
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports: ["8093:8093"]
    depends_on: []

  w4:
    build:
      context: ..
      dockerfile: services/witness-node/Dockerfile
    environment:
      - PORT=8094
      - WITNESS_ID=w4
      - OTEL_ENABLED=1
      - OTEL_SERVICE_NAME=atlas-w4
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports: ["8094:8094"]
    depends_on: []

  w5:
    build:
      context: ..
      dockerfile: services/witness-node/Dockerfile
    environment:
      - PORT=8095
      - WITNESS_ID=w5
      - OTEL_ENABLED=1
      - OTEL_SERVICE_NAME=atlas-w5
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports: ["8095:8095"]
    depends_on: []
