version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - '16686:16686' # UI
      - '4317:4317'   # OTLP gRPC (optional)
      - '4318:4318'   # OTLP HTTP

  gateway:
    build: 
      context: ../
      dockerfile: services/gateway/Dockerfile
    environment:
      OTEL_ENABLED: '1'
      OTEL_SERVICE_NAME: 'atlas-gateway'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://jaeger:4318'
      WITNESSES: 'http://w1:8091'
      QUORUM: '1'
      DELTA_MS: '2000'
    ports: 
      - '8080:8080'
    depends_on: 
      - jaeger
      - w1

  w1:
    build: 
      context: ../
      dockerfile: services/witness-node/Dockerfile
    environment:
      OTEL_ENABLED: '1'
      OTEL_SERVICE_NAME: 'atlas-w1'
      WITNESS_ID: 'w1'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://jaeger:4318'
      PORT: '8091'
    ports: 
      - '8091:8091'
    depends_on: 
      - jaeger
