server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: atlasservices
    static_configs:
      - targets:
          - localhost
        labels:
          job: atlasservices
          __path__: /var/log/atlas/*.log

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/log/docker.log

  - job_name: journal
    journal:
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__boot_id']
        target_label: 'boot_id'
      - source_labels: ['__journal__transport']
        target_label: 'transport'
      - source_labels: ['__journal__machine_id']
        target_label: 'machine_id'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
      - source_labels: ['__journal__systemd_cgroup']
        target_label: 'systemd_cgroup'
      - source_labels: ['__journal__systemd_slice']
        target_label: 'systemd_slice'
      - source_labels: ['__journal__systemd_user_unit']
        target_label: 'systemd_user_unit'
      - source_labels: ['__journal__systemd_session']
        target_label: 'systemd_session'
      - source_labels: ['__journal__systemd_owner_uid']
        target_label: 'systemd_owner_uid'
      - source_labels: ['__journal__systemd_user_slice']
        target_label: 'systemd_user_slice'
      - source_labels: ['__journal__systemd_invocation_id']
        target_label: 'systemd_invocation_id'
      - source_labels: ['__journal__systemd_user_invocation_id']
        target_label: 'systemd_user_invocation_id'
      - source_labels: ['__journal__systemd_unit']
        target_label: 'systemd_unit'
      - source_labels: ['__journal__systemd_user_unit']
        target_label: 'systemd_user_unit'
      - source_labels: ['__journal__systemd_session']
        target_label: 'systemd_session'
      - source_labels: ['__journal__systemd_user_session']
        target_label: 'systemd_user_session'
      - source_labels: ['__journal__systemd_owner_uid']
        target_label: 'systemd_owner_uid'
      - source_labels: ['__journal__systemd_user_owner_uid']
        target_label: 'systemd_user_owner_uid'
      - source_labels: ['__journal__systemd_slice']
        target_label: 'systemd_slice'
      - source_labels: ['__journal__systemd_user_slice']
        target_label: 'systemd_user_slice'
      - source_labels: ['__journal__systemd_invocation_id']
        target_label: 'systemd_invocation_id'
      - source_labels: ['__journal__systemd_user_invocation_id']
        target_label: 'systemd_user_invocation_id'
      - source_labels: ['__journal__systemd_unit']
        target_label: 'systemd_unit'
      - source_labels: ['__journal__systemd_user_unit']
        target_label: 'systemd_user_unit'
      - source_labels: ['__journal__systemd_session']
        target_label: 'systemd_session'
      - source_labels: ['__journal__systemd_user_session']
        target_label: 'systemd_user_session'
      - source_labels: ['__journal__systemd_owner_uid']
        target_label: 'systemd_owner_uid'
      - source_labels: ['__journal__systemd_user_owner_uid']
        target_label: 'systemd_user_owner_uid'
      - source_labels: ['__journal__systemd_slice']
        target_label: 'systemd_slice'
      - source_labels: ['__journal__systemd_user_slice']
        target_label: 'systemd_user_slice'
      - source_labels: ['__journal__systemd_invocation_id']
        target_label: 'systemd_invocation_id'
      - source_labels: ['__journal__systemd_user_invocation_id']
        target_label: 'systemd_user_invocation_id'
