apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chat-delivery
  labels:
    app: atlas
    service: chat-delivery
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: PLACEHOLDER_IMAGE_URL
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: SERVICE_NAME
              value: "chat-delivery"
            - name: JWKS_PRIVATE_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: jwks-signing-key-id
                  key: kid
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-connection
                  key: url
            - name: FIRESTORE_PROJECT_ID
              value: "PLACEHOLDER_PROJECT_ID"
          ports:
            - containerPort: 8080
              protocol: TCP
