apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: identity
  labels:
    app: atlas
    service: identity
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: PLACEHOLDER_IMAGE_URL
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: SERVICE_NAME
              value: "identity"
          ports:
            - containerPort: 8080
