apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: key-directory
  labels:
    app: atlas
    service: key-directory
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: PLACEHOLDER_IMAGE_URL
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: SERVICE_NAME
              value: "key-directory"
            - name: KEY_ROTATION_DAYS
              value: "30"
            - name: JWKS_CACHE_TTL
              value: "3600"
          ports:
            - containerPort: 8080
