// Set app name for Atlas security configuration
process.env.ATLAS_APP_NAME = 'proof_messenger';

// Atlas security configuration
let atlasSecurityConfig = null;
try {
  atlasSecurityConfig = require('../../libs/atlas-security.js');
  console.log('🛡️  Proof Messenger: Loaded Atlas security configuration');
} catch (error) {
  console.warn('🛡️  Proof Messenger: Atlas security config not available, using fallback headers');
}

const withPWA = require('next-pwa')({
  dest: 'public',
  // Force-disable PWA to prevent autogenerated manifest/icon refs that cause 404s in production
  disable: true,
  register: true,
  skipWaiting: true,
  runtimeCaching: [
    {
      urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
      handler: 'CacheFirst',
      options: {
        cacheName: 'google-fonts',
        expiration: {
          maxEntries: 4,
          maxAgeSeconds: 365 * 24 * 60 * 60, // 365 days
        },
      },
    },
    {
      urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
      handler: 'CacheFirst',
      options: {
        cacheName: 'google-fonts-static',
        expiration: {
          maxEntries: 4,
          maxAgeSeconds: 365 * 24 * 60 * 60, // 365 days
        },
      },
    },
    {
      urlPattern: /\.(?:eot|otf|ttc|ttf|woff|woff2|font.css)$/i,
      handler: 'StaleWhileRevalidate',
      options: {
        cacheName: 'static-font-assets',
        expiration: {
          maxEntries: 4,
          maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
        },
      },
    },
    {
      urlPattern: /\.(?:jpg|jpeg|gif|png|svg|ico|webp)$/i,
      handler: 'StaleWhileRevalidate',
      options: {
        cacheName: 'static-image-assets',
        expiration: {
          maxEntries: 64,
          maxAgeSeconds: 24 * 60 * 60, // 24 hours
        },
      },
    },
    {
      urlPattern: /\/_next\/image\?url=.+$/i,
      handler: 'StaleWhileRevalidate',
      options: {
        cacheName: 'next-image',
        expiration: {
          maxEntries: 64,
          maxAgeSeconds: 24 * 60 * 60, // 24 hours
        },
      },
    },
    {
      urlPattern: /^\/api\/.*/i,
      handler: 'NetworkFirst',
      method: 'GET',
      options: {
        cacheName: 'apis',
        expiration: {
          maxEntries: 16,
          maxAgeSeconds: 24 * 60 * 60, // 24 hours
        },
        networkTimeoutSeconds: 10, // fall back to cache if api does not response within 10 seconds
      },
    },
    {
      urlPattern: /.*/i,
      handler: 'NetworkFirst',
      options: {
        cacheName: 'others',
        expiration: {
          maxEntries: 32,
          maxAgeSeconds: 24 * 60 * 60, // 24 hours
        },
        networkTimeoutSeconds: 10,
      },
    },
  ],
});

const path = require('path');

/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
    '@atlas/ui',
    '@atlas/ui-primitives', 
    '@atlas/ui-system',
    '@atlas/ui-tokens',
    '@atlas/config',
    '@atlas/core',
    '@atlas/db',
    '@atlas/mls-core',
    '@atlas/receipt',
    '@atlas/design-system'
  ],
  outputFileTracingRoot: path.join(__dirname, '../../'),
  experimental: {
  async headers() {
    // Use Atlas security configuration if available
    if (atlasSecurityConfig && atlasSecurityConfig.getSecurityHeaders) {
      try {
        const securityHeaders = atlasSecurityConfig.getSecurityHeaders();
        console.log(`🛡️  Proof Messenger: Loaded ${securityHeaders.length} security headers from flags`);
        
        return [
          {
            source: '/(.*)',
            headers: securityHeaders,
          },
        ];
      } catch (error) {
        console.error('Failed to load security headers from flags, using safe defaults:', error);
      }
    }
    
    // Fallback to safe default headers
    console.log('🛡️  Proof Messenger: Using fallback security headers');
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=31536000; includeSubDomains',
          },
          // Safe CSP without advanced features
          {
            key: 'Content-Security-Policy',
            value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.vercel.app https://*.workers.dev; frame-ancestors 'none';"
          }
        ]
      }
    ];
  },
  env: {
    ATLAS_GATEWAY_URL: process.env.ATLAS_GATEWAY_URL || 'https://atlas-gateway.sonthenguyen186.workers.dev',
    ATLAS_DRIVE_URL: process.env.ATLAS_DRIVE_URL || 'https://atlas-gateway.sonthenguyen186.workers.dev',
  },
  // Disable static export to allow dynamic rendering
  // output: 'export', // DISABLED - prevents dynamic rendering
  trailingSlash: true,
  images: {
    unoptimized: false, // Re-enable image optimization
  },
  // Build healing: disable type checking and eslint during builds
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  webpack: (config) => {
    config.resolve.symlinks = false;
    // Exclude crypto package from browser bundles
    config.resolve.alias = {
      ...config.resolve.alias,
      '@atlas/fabric-crypto': false,
      'fabric-crypto': false,
    };
    return config;
  },

};

// Export plain Next config to avoid next-pwa manifest/icon generation on production
module.exports = nextConfig;

