[package]
name = "atlas-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
sha2 = "0.10"
hex = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]