name: Atlas Repository Inventory

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths: ['package.json', 'pnpm-workspace.yaml', '**/tsconfig*.json']
  schedule:
    - cron: '0 6 * * *'  # Daily security scan

# Security: Minimal permissions for inventory scanning
permissions:
  contents: read
  security-events: write
  issues: write
  pull-requests: write

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 9
          run_install: false
      
      - name: Generate repository inventory
        run: |
          # Create evidence directory
          timestamp=$(date -u +"%Y%m%d-%H%M")
          evidence_dir="docs/evidence/$timestamp"
          mkdir -p "$evidence_dir"
          
          # Scan workspace packages
          pnpm -w list -r --depth -1 --json > "$evidence_dir/workspace.json" 2>&1 || echo "Workspace scan failed"
          
          # Find all TypeScript configs
          find . -name "tsconfig*.json" -not -path "./node_modules/*" | jq -R -s 'split("\n")[:-1]' > "$evidence_dir/tsconfigs.json"
          
          # Search for Prism markers
          grep -r "ATLAS • Prism UI — Peak Preview" apps/ --include="*.tsx" --include="*.ts" --include="*.js" > "$evidence_dir/prism-markers.txt" 2>/dev/null || echo "No prism markers found" > "$evidence_dir/prism-markers.txt"
          
          # Generate scan report
          cat > "$evidence_dir/SCAN.md" << 'EOF'
          # Atlas Repository Inventory
          
          **Generated:** $(date -u)  
          **Runner:** ${{ runner.os }} - GitHub Actions
          
          ## Apps Structure
          ```bash
          $(find apps/ -name "package.json" -exec dirname {} \; 2>/dev/null | sort)
          ```
          
          ## Packages Structure  
          ```bash
          $(find packages/ -name "package.json" -exec dirname {} \; 2>/dev/null | sort)
          ```
          
          ## Services Structure
          ```bash
          $(find services/ -name "package.json" -exec dirname {} \; 2>/dev/null | sort)
          ```
          
          ## TypeScript Configurations
          ```bash
          $(find . -name "tsconfig*.json" -not -path "./node_modules/*" | head -20)
          ```
          
          ## Prism Marker Status
          ```
          $(cat "$evidence_dir/prism-markers.txt")
          ```
          
          ## Next.js Apps Detection
          ```bash
          $(find apps/ -name "next.config.*" -exec dirname {} \; 2>/dev/null | sort)
          ```
          EOF
          
          # Generate comprehensive JSON inventory
          cat > "$evidence_dir/repo-inventory.json" << 'EOF'
          {
            "timestamp": "'$timestamp'",
            "runner": "${{ runner.os }}",
            "apps": $(find apps/ -name "package.json" -exec sh -c 'echo "{\"path\":\"$(dirname {})\",\"name\":\"$(jq -r .name {})\"}"' \; 2>/dev/null | jq -s .),
            "packages": $(find packages/ -name "package.json" -exec sh -c 'echo "{\"path\":\"$(dirname {})\",\"name\":\"$(jq -r .name {})\"}"' \; 2>/dev/null | jq -s .),
            "services": $(find services/ -name "package.json" -exec sh -c 'echo "{\"path\":\"$(dirname {})\",\"name\":\"$(jq -r .name {})\"}"' \; 2>/dev/null | jq -s .),
            "tsconfigs": $(find . -name "tsconfig*.json" -not -path "./node_modules/*" | jq -R -s 'split("\n")[:-1]'),
            "nextjs_apps": $(find apps/ -name "next.config.*" -exec dirname {} \; 2>/dev/null | jq -R -s 'split("\n")[:-1]')
          }
          EOF
          
          echo "Evidence generated in $evidence_dir"
          ls -la "$evidence_dir"
      
      - name: Security dependency scan
        uses: github/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a # v4.3.3
        with:
          fail-on-severity: moderate
      
      - name: Upload inventory artifacts
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.6.0
        with:
          name: atlas-inventory-${{ github.run_number }}
          path: docs/evidence/
          retention-days: 30