name: Atlas Insights Observability Smoke
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start stack
        run: |
          docker compose -f observability/docker-compose.insights.yml up -d --build jaeger otel-collector prometheus grafana w1 w2 w3 w4 w5
          for i in {1..60}; do curl -fsS http://localhost:3007/login && break || sleep 2; done
      - name: Verify dashboard exists
        run: |
          curl -fsS "http://admin:admin@localhost:3007/api/search?query=Witness%20p95%2Fp99%20Latency%20%26%20Error" | jq -e '.[0].uid == "witness-latency"'
      - name: Generate traffic
        run: |
          for port in 8091 8092 8093 8094 8095; do
            for i in {1..3}; do curl -fsS -X POST "http://localhost:${port}/witness/record" -H 'content-type: application/json' -d '{"app":"ci","record_id":"run-'"$i"'","payload":"ok","meta":{"ci":true}}' || true; done
          done
          sleep 10
      - name: Verify traces
        run: |
          for s in atlas-w1 atlas-w2 atlas-w3 atlas-w4 atlas-w5; do
            n=$(curl -fsS "http://localhost:16686/api/traces?service=$s&limit=1" | jq -r '.data | length');
            echo "$s traces=$n"; test "$n" -ge 1;
          done
      - name: Verify spanmetrics exist
        run: |
          q='sum by (service) (rate(traces_spanmetrics_calls_total[5m]))'
          curl -fsS --data-urlencode "query=$q" http://localhost:9090/api/v1/query | jq -e '.data.result | length >= 1'
