name: build-selfheal
on:
  push:
    branches: [ main, fix/**, feat/** ]
  pull_request:
    branches: [ main, fix/**, feat/** ]

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable corepack
        run: corepack enable

      - name: Install deps (no frozen)
        run: pnpm install --no-frozen-lockfile

      - name: Build fabric-protocol
        run: pnpm -F @atlas/fabric-protocol build || true

      - name: Build witness-node (tsc noEmit fallback)
        run: pnpm -F @atlas/witness-node build || (cd services/witness-node && npx tsc --noEmit)

      - name: Capture logs
        if: always()
        run: |
          mkdir -p scripts/ci
          echo "Build logs captured" > scripts/ci/last.log

      - name: Upload artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-selfheal-logs
          path: |
            scripts/ci/last.log