    - name: Test observability endpoints
      run: |
        # Test Jaeger
        curl -f http://localhost:16686 || exit 1
        
        # Test Prometheus
        curl -f http://localhost:9090 || exit 1
        
        # Test Grafana
        curl -f http://localhost:3000 || exit 1
        
        # Test OpenTelemetry Collector
        curl -f http://localhost:4318/v1/traces || exit 1
        
        # Test Tempo
        curl -f http://localhost:3200 || exit 1