name: CI Observability

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  observability-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.0.0
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build services
      run: pnpm build
      
    - name: Start observability stack
      run: |
        docker-compose -f docker-compose.observability.yml up -d
        sleep 30
        
    - name: Test observability endpoints
      run: |
        # Test Jaeger
        curl -f http://localhost:16686 || exit 1
        
        # Test Prometheus
        curl -f http://localhost:9090 || exit 1
        
        # Test Grafana
        curl -f http://localhost:3000 || exit 1
        
        # Test OpenTelemetry Collector
        curl -f http://localhost:4318/v1/traces || exit 1
        
        # Test Tempo
        curl -f http://localhost:3200 || exit 1
        
    - name: Test service observability
      run: |
        # Start services in background
        cd services/gateway && pnpm start &
        GATEWAY_PID=$!
        
        cd services/witness-node && pnpm start &
        WITNESS_PID=$!
        
        # Wait for services to start
        sleep 10
        
        # Test health endpoints
        curl -f http://localhost:8080/health || exit 1
        curl -f http://localhost:8091/witness/health || exit 1
        
        # Test metrics endpoints
        curl -f http://localhost:8080/metrics || exit 1
        curl -f http://localhost:8091/witness/stats || exit 1
        
        # Cleanup
        kill $GATEWAY_PID $WITNESS_PID || true
        
    - name: Cleanup
      if: always()
      run: |
        docker-compose -f docker-compose.observability.yml down