name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Run unit tests
        run: pnpm -r test -- --ci --reporters=default

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Restore dist artifacts from previous step (optional)
        run: |
          echo "(dist present in repo checkout)"

      - name: Docker info
        run: |
          docker --version
          docker compose version || docker-compose --version || true

      - name: Build services
        run: docker compose -f infra/docker/compose.ci.yml build --no-cache

      - name: Up services
        run: docker compose -f infra/docker/compose.ci.yml up -d

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke
        run: chmod +x scripts/smoke.sh && ./scripts/smoke.sh http://localhost:8080

      - name: Logs on failure
        if: failure()
        run: |
          docker ps -a
          docker compose -f infra/docker/compose.ci.yml logs --tail=200

      - name: Stop services
        if: always()
        run: docker compose -f infra/docker/compose.ci.yml down -v

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, test, integration-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/*/dist
            services/*/dist
            apps/*/.next
          retention-days: 7

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, test, integration-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images (no push)
        run: |
          docker build -f services/gateway/Dockerfile -t test/gateway:pr .
          docker build -f services/witness-node/Dockerfile -t test/witness:pr .

  sec-verify:
    name: Security Verify
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3
      - uses: imjasonh/setup-crane@v0.4
      - name: Resolve digests for :latest
        id: dig
        run: |
          echo "gw=$(crane digest ghcr.io/${{ github.repository_owner }}/atlas-gateway:latest)" >> $GITHUB_OUTPUT
          echo "wt=$(crane digest ghcr.io/${{ github.repository_owner }}/atlas-witness:latest)" >> $GITHUB_OUTPUT
      - name: cosign verify latest
        env: { COSIGN_EXPERIMENTAL: 1 }
        run: |
          cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com ghcr.io/${{ github.repository_owner }}/atlas-gateway@${{ steps.dig.outputs.gw }}
          cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com ghcr.io/${{ github.repository_owner }}/atlas-witness@${{ steps.dig.outputs.wt }}
