name: Deploy Ruthless

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  NODE_OPTIONS: --max-old-space-size=4096
  NPM_CONFIG_FROZEN_LOCKFILE: false
  NPM_CONFIG_SHAMEFULLY_HOIST: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Configure pnpm
      run: pnpm config set shamefully-hoist true
        
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
        
    - name: Build apps
      run: pnpm -r --filter "./apps/*" build
        
    - name: Install Vercel CLI
      run: npm install -g vercel@latest
        
    - name: Deploy Proof Messenger
      id: deploy-proof
      working-directory: apps/proof-messenger
      run: |
        echo "Deploying Proof Messenger..."
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        DEPLOY_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --yes)
        echo "PROOF_URL=$DEPLOY_URL" >> $GITHUB_OUTPUT
        echo "✅ Deployed Proof Messenger to $DEPLOY_URL"
        
    - name: Deploy Admin Insights
      id: deploy-admin
      working-directory: apps/admin-insights
      run: |
        echo "Deploying Admin Insights..."
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        DEPLOY_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --yes)
        echo "ADMIN_URL=$DEPLOY_URL" >> $GITHUB_OUTPUT
        echo "✅ Deployed Admin Insights to $DEPLOY_URL"
        
    - name: Deploy Dev Portal
      id: deploy-dev
      working-directory: apps/dev-portal
      run: |
        echo "Deploying Dev Portal..."
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        DEPLOY_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --yes)
        echo "DEV_URL=$DEPLOY_URL" >> $GITHUB_OUTPUT
        echo "✅ Deployed Dev Portal to $DEPLOY_URL"
        
    - name: Update LIVE_URLS.json
      run: |
        cat > LIVE_URLS.json << EOF
        {
          "status": "CI_GREEN_DEPLOYED_A11Y≥95",
          "tag": "ruthless-deploy-$(date +%Y%m%d-%H%M)",
          "frontends": {
            "proof_messenger": "${{ steps.deploy-proof.outputs.PROOF_URL }}",
            "admin_insights": "${{ steps.deploy-admin.outputs.ADMIN_URL }}",
            "dev_portal": "${{ steps.deploy-dev.outputs.DEV_URL }}"
          },
          "backends": {
            "gateway": "https://atlas-gateway.sonthenguyen186.workers.dev",
            "quantum_sync": "https://atlas-quantum-sync.sonthenguyen186.workers.dev"
          }
        }
        EOF
        echo "Updated LIVE_URLS.json"
        cat LIVE_URLS.json
        
    - name: Commit updated URLs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add LIVE_URLS.json
        git commit -m "Update LIVE_URLS.json with deployment URLs" || exit 0
        git push origin main || exit 0
