name: Nightly Lighthouse CI

on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      
      - name: Run Lighthouse CI
        run: |
          lhci autorun --upload.target=filesystem --upload.outputDir=./lighthouse-reports
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      
      - name: Create evidence directory
        run: |
          mkdir -p docs/evidence/$(date -u +"%Y%m%d-%H%M")/lighthouse/
          cp -r lighthouse-reports/* docs/evidence/$(date -u +"%Y%m%d-%H%M")/lighthouse/
      
      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lighthouse-reports/