name: postdeploy-audit
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag"
        required: false
        default: "main"
jobs:
  nav-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { ref: ${{ github.event.inputs.ref || 'main' }} }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - name: Run asset-aware NAV audit
        run: node scripts/replan-nav-audit.js
      - name: Enforce non200 == 0
        run: |
          node -e "const fs=require('fs');const p='docs/REPLAN/NAV_AUDIT.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));const n=(j.non200??j.summary?.non200??j.overall?.non200??0); if(n>0){console.log('BLOCKER_NAV_ASSETS: non200='+n); process.exit(2);} console.log('NAV_OK');"
      - uses: actions/upload-artifact@v4
        with:
          name: nav-audit
          path: |
            docs/REPLAN/NAV_AUDIT.json
            docs/evidence/**/nav_audit.json