name: Secrets Audit

on:
  push:
    branches: [ga/merge-security-core-20251022-1618]
  workflow_dispatch: {}

jobs:
  audit:
    name: Verify GCP Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check required GitHub Secrets exist
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_DEPLOYER_SA: ${{ secrets.GCP_DEPLOYER_SA }}
          GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
          GCP_WORKLOAD_ID_PROVIDER: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
        run: |
          required=(GCP_PROJECT_ID GCP_REGION GCP_DEPLOYER_SA GCP_PROJECT_NUMBER GCP_WORKLOAD_ID_PROVIDER)
          missing=0
          for k in "${required[@]}"; do
            if [ -z "${!k}" ]; then
              echo "::error title=Missing secret::${k} is not set in repo secrets"
              missing=1
            else
              echo "::notice::${k} is present (length: ${#!k} chars)"
            fi
          done
          
          if [ $missing -eq 1 ]; then
            echo "::error::❌ Some required secrets are missing. Configure at: https://github.com/${{ github.repository }}/settings/secrets/actions"
            exit 1
          else
            echo "::notice::✅ All required GCP secrets are configured"
          fi
