name: Secrets Smoke Test v4

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check VERCEL_TOKEN
        run: echo "VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN != '' }}"
      - name: Check VERCEL_ORG_ID
        run: echo "VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID != '' }}"
      - name: Check VERCEL_PROJECT_ID_PROOF
        run: echo "VERCEL_PROJECT_ID_PROOF: ${{ secrets.VERCEL_PROJECT_ID_PROOF != '' }}"
      - name: Check VERCEL_PROJECT_ID_INSIGHTS
        run: echo "VERCEL_PROJECT_ID_INSIGHTS: ${{ secrets.VERCEL_PROJECT_ID_INSIGHTS != '' }}"
      - name: Check VERCEL_PROJECT_ID_DEVPORTAL
        run: echo "VERCEL_PROJECT_ID_DEVPORTAL: ${{ secrets.VERCEL_PROJECT_ID_DEVPORTAL != '' }}"
