name: Secrets Smoke Test
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Secrets
        run: |
          echo "VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN != '' }}"
          echo "VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID != '' }}"
          echo "VERCEL_PROJECT_ID_PROOF: ${{ secrets.VERCEL_PROJECT_ID_PROOF != '' }}"
          echo "VERCEL_PROJECT_ID_INSIGHTS: ${{ secrets.VERCEL_PROJECT_ID_INSIGHTS != '' }}"
          echo "VERCEL_PROJECT_ID_DEVPORTAL: ${{ secrets.VERCEL_PROJECT_ID_DEVPORTAL != '' }}"
          
          # Check required secrets
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "BLOCKER_MISSING_SECRET:VERCEL_TOKEN"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "BLOCKER_MISSING_SECRET:VERCEL_ORG_ID"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID_PROOF }}" ]; then
            echo "BLOCKER_MISSING_SECRET:VERCEL_PROJECT_ID_PROOF"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID_INSIGHTS }}" ]; then
            echo "BLOCKER_MISSING_SECRET:VERCEL_PROJECT_ID_INSIGHTS"
            exit 1
          fi
          # VERCEL_PROJECT_ID_DEVPORTAL is optional
          
          echo "All required secrets present"
