name: test-verify
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to verify"
        required: true
        default: "v0.1.7"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: imjasonh/setup-crane@v0.4
      - name: Test crane access
        run: |
          echo "Testing crane access to GHCR"
          crane ls ghcr.io/pussycat186/atlas-gateway | head -5
          crane ls ghcr.io/pussycat186/atlas-witness | head -5
      - name: Test digest resolution
        run: |
          echo "Testing digest resolution for tag: ${{ inputs.tag }}"
          crane digest ghcr.io/pussycat186/atlas-gateway:${{ inputs.tag }} || echo "Gateway digest failed"
          crane digest ghcr.io/pussycat186/atlas-witness:${{ inputs.tag }} || echo "Witness digest failed"
