name: test-verify-signed
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to verify"
        required: true
        default: "v0.1.7"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3
      - uses: imjasonh/setup-crane@v0.4
      - name: Get digests
        run: |
          echo "gw=$(crane digest ghcr.io/${{ github.repository_owner }}/atlas-gateway:${{ inputs.tag }})" >> $GITHUB_OUTPUT
          echo "wt=$(crane digest ghcr.io/${{ github.repository_owner }}/atlas-witness:${{ inputs.tag }})" >> $GITHUB_OUTPUT
        id: digests
      - name: Test cosign verify
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          echo "Testing cosign verification..."
          echo "Gateway digest: ${{ steps.digests.outputs.gw }}"
          echo "Witness digest: ${{ steps.digests.outputs.wt }}"
          # Test verification
          cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com ghcr.io/${{ github.repository_owner }}/atlas-gateway@${{ steps.digests.outputs.gw }} || echo "Gateway verification failed"
          cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com ghcr.io/${{ github.repository_owner }}/atlas-witness@${{ steps.digests.outputs.wt }} || echo "Witness verification failed"
