name: test-release
on:
  push:
    tags:
      - 'test-*'
permissions:
  contents: write
  packages: write
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Test Docker build
        run: |
          docker build -f services/gateway/Dockerfile -t test/gateway:test .
          docker build -f services/witness-node/Dockerfile -t test/witness:test .
