name: verify-release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to verify (default: latest)"
        required: false
        default: latest
permissions:
  contents: read
  packages: read
  id-token: write
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      TAG: ${{ inputs.tag || 'latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install crane
        uses: imjasonh/setup-crane@v0.4

      - name: Resolve digests
        id: dig
        run: |
          set -euo pipefail
          echo "gw=$(crane digest ghcr.io/${OWNER}/atlas-gateway:${TAG})" >> $GITHUB_OUTPUT
          echo "wt=$(crane digest ghcr.io/${OWNER}/atlas-witness:${TAG})" >> $GITHUB_OUTPUT
          echo "Gateway: ${{ 'ghcr.io/' }}${OWNER}/atlas-gateway:${TAG} -> ${{ steps.dig.outputs.gw }}"
          echo "Witness: ${{ 'ghcr.io/' }}${OWNER}/atlas-witness:${TAG} -> ${{ steps.dig.outputs.wt }}"

      - name: Cosign verify (gateway)
        env: { COSIGN_EXPERIMENTAL: 1 }
        run: |
          set -euo pipefail
          cosign verify \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            ghcr.io/${OWNER}/atlas-gateway@${{ steps.dig.outputs.gw }}

      - name: Cosign verify (witness)
        env: { COSIGN_EXPERIMENTAL: 1 }
        run: |
          set -euo pipefail
          cosign verify \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            ghcr.io/${OWNER}/atlas-witness@${{ steps.dig.outputs.wt }}

      - name: Verify SLSA provenance (gateway)
        uses: slsa-framework/slsa-verifier/actions/verify-artifact@v2.6.0
        with:
          subject-name: ghcr.io/${{ env.OWNER }}/atlas-gateway
          subject-digest: ${{ steps.dig.outputs.gw }}

      - name: Verify SLSA provenance (witness)
        uses: slsa-framework/slsa-verifier/actions/verify-artifact@v2.6.0
        with:
          subject-name: ghcr.io/${{ env.OWNER }}/atlas-witness
          subject-digest: ${{ steps.dig.outputs.wt }}