name: verify-ghcr
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to verify'
        required: true
        default: 'v0.1.7'
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: imjasonh/setup-crane@v0.4
      - name: List GHCR tags
        run: |
          echo "=== Gateway Images ==="
          crane ls ghcr.io/pussycat186/atlas-gateway | tail -n +1
          echo "=== Witness Images ==="
          crane ls ghcr.io/pussycat186/atlas-witness | tail -n +1
      - name: Get image digests
        run: |
          echo "=== Gateway Digest ==="
          crane digest ghcr.io/pussycat186/atlas-gateway:${{ github.event.inputs.tag }}
          echo "=== Witness Digest ==="
          crane digest ghcr.io/pussycat186/atlas-witness:${{ github.event.inputs.tag }}
